# Generated by Django 4.2 on 2023-04-12 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductoresApp', '0002_rename_identificaion_conductor_identicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=4, verbose_name='Modelo')),
                ('placa', models.CharField(max_length=7, verbose_name='Nombre')),
                ('capacidad', models.CharField(max_length=7, verbose_name='Apellido')),
                ('conductor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conductoresApp.conductor')),
            ],
        ),
    ]
