# Generated by Django 4.2 on 2023-04-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0002_alter_vehiculo_capacidad_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='id',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
