# Generated by Django 4.2 on 2023-04-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0003_alter_vehiculo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='conductor_id',
            new_name='conductor',
        ),
    ]
