# Generated by Django 4.2 on 2023-04-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('identificaion', models.CharField(max_length=11, unique=True, verbose_name='Identificacion')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=50, unique=True, verbose_name='Direccion')),
            ],
        ),
    ]
