# Generated by Django 4.2 on 2023-04-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conductoresApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='identificaion',
            new_name='identicacion',
        ),
    ]
